### ISSUE TITLE
Scrappy didn’t reset my Slack status after I broke my streak

### ISSUE THREAD

**Issue by zachlatta** [hackclub/scrappy#36] opened 2020-06-28 18:58 UTC
Here’s what happened:

1. Posted on Thursday (day 1 of streak). Slack status got set.
2. Posted on Friday (day 2 of streak). Slack status got set
3. Forgot to post on Saturday (would have been day 3).
4. Notice at 2:56 PM ET on Sunday that Scrappy hasn’t removed my streak from my Slack status.
5. Toggle my streak showing with /scrappy displaystreaks (ran twice). Notice that since I missed my post yesterday, my Slack status didn’t get set to anything as expected

**Comment by MatthewStanciu** [comment] 2020-06-28 19:20
I've noticed that occasionally Scrappy doesn't properly increment people's statuses when they post, which leads me to believe that the issue is with my `setStatus()` method. I believe this can be fixed by `await`ing the API call to Slack in the function, which I just added. I can't be sure the issue was fixed, though, because it happens so rarely and sporadically that I can't feasibly reproduce it.

To keep the Issues tab clean, I'm going to go ahead and close the issue—but @zachlatta if you notice your or other people's statuses not being properly updated, please reopen and I'll investigate further. I'll also be on the lookout and reopen if needed.

**Comment by MatthewStanciu** [comment] 2020-06-30 14:54
Looks like it didn't reset my streak either :( looking into this today

**Comment by MatthewStanciu** [comment] 2020-07-02 14:55
Closing again because I'm pretty sure this time the issue was #46. Will reopen if I see it happen again though

**Closed by MatthewStanciu** 2020-07-02 14:55 UTC
